"""
Base de datos de productos española - VERSIÓN AMPLIADA
Diccionario completo con 250+ productos
"""
from typing import Dict, Tuple

# Diccionario: {nombre: (categoría, días_caducidad, ubicación)}
PRODUCT_DATABASE: Dict[str, Tuple[str, int, str]] = {
    # ==================== FRUTAS ====================
    "naranja": ("fruits", 14, "fridge"),
    "manzana": ("fruits", 14, "fridge"),
    "platano": ("fruits", 7, "pantry"),
    "plátano": ("fruits", 7, "pantry"),
    "pera": ("fruits", 10, "fridge"),
    "mandarina": ("fruits", 14, "fridge"),
    "limon": ("fruits", 21, "fridge"),
    "limón": ("fruits", 21, "fridge"),
    "fresa": ("fruits", 3, "fridge"),
    "kiwi": ("fruits", 10, "fridge"),
    "melon": ("fruits", 7, "fridge"),
    "melón": ("fruits", 7, "fridge"),
    "sandia": ("fruits", 7, "fridge"),
    "sandía": ("fruits", 7, "fridge"),
    "uva": ("fruits", 7, "fridge"),
    "piña": ("fruits", 7, "fridge"),
    "mango": ("fruits", 7, "fridge"),
    "aguacate": ("fruits", 5, "pantry"),
    "malla": ("fruits", 14, "fridge"),
    
    # ==================== VERDURAS ====================
    "tomate": ("vegetables", 7, "fridge"),
    "lechuga": ("vegetables", 5, "fridge"),
    "pepino": ("vegetables", 7, "fridge"),
    "cebolla": ("vegetables", 21, "pantry"),
    "ajo": ("vegetables", 30, "pantry"),
    "zanahoria": ("vegetables", 14, "fridge"),
    "pimiento": ("vegetables", 10, "fridge"),
    "calabacin": ("vegetables", 7, "fridge"),
    "calabacín": ("vegetables", 7, "fridge"),
    "berenjena": ("vegetables", 7, "fridge"),
    "brocoli": ("vegetables", 7, "fridge"),
    "brócoli": ("vegetables", 7, "fridge"),
    "coliflor": ("vegetables", 10, "fridge"),
    "espinaca": ("vegetables", 5, "fridge"),
    "acelga": ("vegetables", 5, "fridge"),
    "patata": ("vegetables", 30, "pantry"),
    "batata": ("vegetables", 21, "pantry"),
    "puerro": ("vegetables", 10, "fridge"),
    "champiñon": ("vegetables", 5, "fridge"),
    "champiñón": ("vegetables", 5, "fridge"),
    "seta": ("vegetables", 5, "fridge"),
    "setas": ("vegetables", 5, "fridge"),
    
    # ==================== LÁCTEOS Y HUEVOS ====================
    "leche": ("dairy", 7, "fridge"),
    "yogur": ("dairy", 21, "fridge"),
    "queso": ("dairy", 21, "fridge"),
    "mantequilla": ("dairy", 30, "fridge"),
    "nata": ("dairy", 10, "fridge"),
    "crema": ("dairy", 10, "fridge"),
    "natilla": ("dairy", 10, "fridge"),
    "flan": ("dairy", 10, "fridge"),
    "cuajada": ("dairy", 10, "fridge"),
    "huevo": ("dairy", 28, "fridge"),
    "huevos": ("dairy", 28, "fridge"),
    
    # ==================== CARNES Y EMBUTIDOS ====================
    "pollo": ("meat", 3, "fridge"),
    "pavo": ("meat", 3, "fridge"),
    "ternera": ("meat", 3, "fridge"),
    "cerdo": ("meat", 3, "fridge"),
    "cordero": ("meat", 3, "fridge"),
    "carne": ("meat", 3, "fridge"),
    "filete": ("meat", 3, "fridge"),
    "chuleta": ("meat", 3, "fridge"),
    "hamburguesa": ("meat", 3, "fridge"),
    "salchicha": ("meat", 7, "fridge"),
    "chorizo": ("meat", 21, "fridge"),
    "jamon": ("meat", 30, "fridge"),
    "jamón": ("meat", 30, "fridge"),
    "bacon": ("meat", 10, "fridge"),
    "pechuga": ("meat", 5, "fridge"),
    "bipack": ("meat", 5, "fridge"),
    
    # ==================== PESCADO ====================
    "pescado": ("fish", 2, "fridge"),
    "salmon": ("fish", 2, "fridge"),
    "salmón": ("fish", 2, "fridge"),
    "merluza": ("fish", 2, "fridge"),
    "atun": ("fish", 2, "fridge"),
    "atún": ("fish", 2, "fridge"),
    "bacalao": ("fish", 2, "fridge"),
    "lubina": ("fish", 2, "fridge"),
    "dorada": ("fish", 2, "fridge"),
    "gamba": ("fish", 2, "fridge"),
    "langostino": ("fish", 2, "fridge"),
    "calamar": ("fish", 2, "fridge"),
    "pulpo": ("fish", 2, "fridge"),
    "mejillon": ("fish", 2, "fridge"),
    "mejillón": ("fish", 2, "fridge"),
    
    # ==================== CEREALES Y LEGUMBRES ====================
    "arroz": ("grains", 365, "pantry"),
    "pasta": ("grains", 365, "pantry"),
    "espagueti": ("grains", 365, "pantry"),
    "macarron": ("grains", 365, "pantry"),
    "macarrón": ("grains", 365, "pantry"),
    "fideos": ("grains", 365, "pantry"),
    "fideo": ("grains", 365, "pantry"),
    "lentejas": ("grains", 365, "pantry"),
    "lenteja": ("grains", 365, "pantry"),
    "garbanzo": ("grains", 365, "pantry"),
    "alubia": ("grains", 365, "pantry"),
    "judias": ("grains", 365, "pantry"),
    "judías": ("grains", 365, "pantry"),
    "quinoa": ("grains", 365, "pantry"),
    "avena": ("grains", 180, "pantry"),
    "cereales": ("grains", 90, "pantry"),
    "harina": ("grains", 180, "pantry"),
    "pardina": ("grains", 365, "pantry"),
    "sos": ("grains", 365, "pantry"),
    
    # ==================== PAN Y PANADERÍA ====================
    "pan": ("bakery", 3, "pantry"),
    "barra": ("bakery", 2, "pantry"),
    "baguette": ("bakery", 2, "pantry"),
    "panecillo": ("bakery", 2, "pantry"),
    "bollo": ("bakery", 5, "pantry"),
    "croissant": ("bakery", 2, "pantry"),
    "magdalena": ("bakery", 10, "pantry"),
    "bizcocho": ("bakery", 10, "pantry"),
    "galleta": ("snacks", 90, "pantry"),
    "tostada": ("bakery", 90, "pantry"),
    "espelta": ("bakery", 3, "pantry"),
    "integral": ("bakery", 3, "pantry"),
    "semillas": ("bakery", 3, "pantry"),
    "empanada": ("bakery", 3, "fridge"),
    "empanada pollo": ("bakery", 3, "fridge"),
    
    # ==================== CONGELADOS ====================
    "helado": ("frozen", 180, "freezer"),
    "pizza": ("frozen", 180, "freezer"),
    "congelado": ("frozen", 180, "freezer"),
    "croqueta": ("frozen", 180, "freezer"),
    "croquetas": ("frozen", 180, "freezer"),
    
    # ==================== BEBIDAS ====================
    "agua": ("beverages", 365, "pantry"),
    "zumo": ("beverages", 30, "fridge"),
    "zumo manzana": ("beverages", 30, "fridge"),
    "zumo naranja": ("beverages", 30, "fridge"),
    "refresco": ("beverages", 180, "pantry"),
    "cola": ("beverages", 180, "pantry"),
    "limonada": ("beverages", 30, "fridge"),
    "cerveza": ("beverages", 180, "pantry"),
    "vino": ("beverages", 730, "pantry"),
    "cafe": ("beverages", 180, "pantry"),
    "café": ("beverages", 180, "pantry"),
    "te": ("beverages", 365, "pantry"),
    "té": ("beverages", 365, "pantry"),
    
    # ==================== CONDIMENTOS ====================
    "aceite": ("condiments", 365, "pantry"),
    "vinagre": ("condiments", 365, "pantry"),
    "sal": ("condiments", 9999, "pantry"),
    "azucar": ("condiments", 365, "pantry"),
    "azúcar": ("condiments", 365, "pantry"),
    "miel": ("condiments", 9999, "pantry"),
    "mayonesa": ("condiments", 180, "pantry"),
    "ketchup": ("condiments", 180, "pantry"),
    "mostaza": ("condiments", 180, "pantry"),
    "salsa": ("condiments", 180, "pantry"),
    "tomate frito": ("condiments", 365, "pantry"),
    "especias": ("condiments", 365, "pantry"),
    "pimienta": ("condiments", 365, "pantry"),
    "oregano": ("condiments", 365, "pantry"),
    "orégano": ("condiments", 365, "pantry"),
    "laurel": ("condiments", 365, "pantry"),
    "cominos": ("condiments", 365, "pantry"),
    
    # ==================== SNACKS ====================
    "patatas fritas": ("snacks", 60, "pantry"),
    "chips": ("snacks", 60, "pantry"),
    "chocolate": ("snacks", 90, "pantry"),
    "caramelo": ("snacks", 180, "pantry"),
    "golosina": ("snacks", 180, "pantry"),
    "turrón": ("snacks", 180, "pantry"),
    "turron": ("snacks", 180, "pantry"),
    "lonchas": ("snacks", 30, "fridge"),
    "lonchas light": ("snacks", 30, "fridge"),
    "queso lonchas": ("dairy", 30, "fridge"),
    
    # ==================== OTROS (Limpieza, higiene) ====================
    "detergente": ("other", 9999, "pantry"),
    "suavizante": ("other", 9999, "pantry"),
    "marsella": ("other", 9999, "pantry"),
    "floral": ("other", 9999, "pantry"),
    "body": ("other", 9999, "pantry"),
    "deo": ("other", 9999, "pantry"),
    "aqua": ("other", 9999, "pantry"),
    "ensaladilla": ("other", 3, "fridge"),
    "conserva": ("other", 365, "pantry"),
    "lata": ("other", 365, "pantry"),
    "bote": ("other", 180, "pantry"),
}

# Palabras clave para categorías
CATEGORY_KEYWORDS = {
    "fruits": ["fruta", "fresco", "natural", "malla"],
    "vegetables": ["verdura", "hortaliza", "vegetal"],
    "dairy": ["lacteo", "lácteo", "cremoso", "huevo"],
    "meat": ["carne", "ave", "embutido", "pavo", "pollo"],
    "fish": ["pescado", "marisco", "marino"],
    "grains": ["cereal", "legumbre", "grano", "seco", "arroz", "pasta"],
    "bakery": ["pan", "reposteria", "repostería", "bollería", "empanada"],
    "beverages": ["bebida", "liquido", "líquido", "zumo"],
    "snacks": ["aperitivo", "snack", "dulce", "lonchas"],
    "condiments": ["condimento", "aderezo", "especia"],
    "frozen": ["congelado", "helado", "croqueta"],
    "other": ["limpieza", "hogar", "higiene", "body", "deo", "detergente", 
              "suavizante", "ensaladilla", "marsella"]
}

# Ubicaciones por defecto
DEFAULT_LOCATIONS = {
    "fruits": "fridge",
    "vegetables": "fridge",
    "dairy": "fridge",
    "meat": "fridge",
    "fish": "fridge",
    "grains": "pantry",
    "bakery": "pantry",
    "beverages": "pantry",
    "snacks": "pantry",
    "condiments": "pantry",
    "frozen": "freezer",
    "other": "pantry"
}

# Días de caducidad por defecto
DEFAULT_EXPIRATION_DAYS = {
    "fruits": 7,
    "vegetables": 5,
    "dairy": 7,
    "meat": 3,
    "fish": 2,
    "grains": 180,
    "bakery": 3,
    "beverages": 90,
    "snacks": 60,
    "condiments": 180,
    "frozen": 180,
    "other": 30
}